services:
  nginx:
    depends_on:
      - backend
      - frontend
    image: nginx:1.25.5-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    networks:
      - longliveprofessorkim

  backend:
    image: cotidie/longliveprofessorkim-backend
    ports:
      - 8080:8080
    container_name: backend
    networks:
      - longliveprofessorkim

  frontend:
    image: public.ecr.aws/c9z7b3l2/frontend
    ports:
      - 3000:3000
    container_name: frontend
    networks:
      - longliveprofessorkim

networks:
  longliveprofessorkim:
