on:
  pull_request:
    branches:
      - main
    types: [labeled]
  
jobs:
  build-image:
    if: github.event.label.name == 'frontend'
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: debug
        uses: actions/checkout@v3

      - name: Build and Push
        id: front-build
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/frontend
          push: true
          tags: cotidie/longliveprofessorkim-frontend



      