on:
  push:
    branches:
      - 'wonseok/deploy-frontend-workflow'
  
jobs:
  build-image:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      