on:
  pull_request:
    branches:
      - main
    types: [labeled]
  
jobs:
  build-image:
    if: github.event.label.name == 'frontend'
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      
      - name: Build and Push docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: llpk-frontend
        run: |
          docker build -t $REGISTRY/$REPOSITORY ./frontend
          docker push $REGISTRY/$REPOSITORY
